# Generated by Django 5.1.2 on 2024-12-13 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileManagerApp', '0002_alter_accesslink_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslink',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 20, 20, 4, 15, 847426, tzinfo=datetime.timezone.utc)),
        ),
    ]
